// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BaseProject.DAO.Models
{
    public partial class DownloadArquivo
    {
        [Key]
        public int IdDownload { get; set; }
        [Required]
        [StringLength(255)]
        public string Nome { get; set; }
        [Required]
        [StringLength(10)]
        public string Extensao { get; set; }
        public int Tamanho { get; set; }
        [Required]
        [StringLength(255)]
        public string Tipo { get; set; }
        [Required]
        public string Base64 { get; set; }

        [ForeignKey("IdDownload")]
        [InverseProperty("DownloadArquivo")]
        public virtual Download IdDownloadNavigation { get; set; }
    }
}