// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BaseProject.DAO.Models
{
    [Index("IdEmpresa", Name = "IX_Download_IdEmpresa")]
    [Index("IdUsuario", Name = "IX_Download_IdUsuario")]
    public partial class Download
    {
        [Key]
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public byte Tipo { get; set; }
        public byte Status { get; set; }
        public DateTime DataInicial { get; set; }
        public DateTime? DataFinal { get; set; }
        public int IdEmpresa { get; set; }

        [ForeignKey("IdEmpresa")]
        [InverseProperty("Download")]
        public virtual Empresa IdEmpresaNavigation { get; set; }
        [ForeignKey("IdUsuario")]
        [InverseProperty("Download")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
        [InverseProperty("IdDownloadNavigation")]
        public virtual DownloadArquivo DownloadArquivo { get; set; }
    }
}