// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BaseProject.DAO.Models
{
    [Index("IdUsuario", Name = "IX_LogAcessoUsuario_IdUsuario")]
    public partial class LogAcessoUsuario
    {
        [Key]
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        [Required]
        [StringLength(255)]
        public string EnderecoIP { get; set; }
        [Required]
        [StringLength(255)]
        public string Dispositivo { get; set; }
        [Required]
        [StringLength(255)]
        public string Plataforma { get; set; }
        [Required]
        [StringLength(255)]
        public string Navegador { get; set; }
        public bool Status { get; set; }
        public DateTime Data { get; set; }

        [ForeignKey("IdUsuario")]
        [InverseProperty("LogAcessoUsuario")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}